import Sidebar from "@/components/common/Sidebar";
import Topbar from "@/components/common/Topbar";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={inter.className}
        style={{
          height: "100%",
        }}
      >
        <div className="flex flex-col h-full p-2 ">
          <div className="w-full py-2">
            <Topbar />
          </div>
          <div className="flex h-full gap-2 ">
            <div className="w-1/4 h-full  rounded-lg">
              <Sidebar />
            </div>
            <div className="w-3/4 rounded-lg pt-2">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
